version: '3.8'

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.23.0/24

volumes:
    postgresdata:
        driver: local

services:
    nginx:
        image: nginx:1.23.1-alpine
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
            - ./docker/nginx/add/:/etc/nginx/add/
            - ./backend/:${SPA_CODE_PATH_CONTAINER}/backend/
            - ./frontend/:${SPA_CODE_PATH_CONTAINER}/frontend/
        ports:
            - ${SPA_NGINX_PORT}:80
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./backend/:${SPA_CODE_PATH_CONTAINER}/backend/
            - ./.env:/etc/environment
        env_file:
            - .env
        environment:
            PHP_IDE_CONFIG: ${SPA_PHP_IDE_CONFIG}
        extra_hosts:
            - host.docker.internal:host-gateway
        working_dir: ${SPA_CODE_PATH_CONTAINER}/backend/
    mysql:
        image: mysql:8
        command: mysqld --sql_mode=""
        ports:
            - "${SPA_MYSQL_PORT}:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./docker/mysql/:/docker-entrypoint-initdb.d/
        environment:
            - "TZ=${SPA_TIMEZONE}"
            - MYSQL_ROOT_PASSWORD=${SPA_MYSQL_PASSWORD}
            - MYSQL_DB=${SPA_MYSQL_DB}
    nodejs:
        build:
            context: docker/nodejs
        ports:
            - "80:8080"
        volumes:
            - ./frontend/:/web/frontend/
            - ./docker/nodejs/docker-entrypoint.sh:/docker-entrypoint.sh
        entrypoint: /docker-entrypoint.sh
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
        working_dir: ${SPA_CODE_PATH_CONTAINER}/frontend/

    composer:
        image: composer
        volumes:
            - ./backend/:${SPA_CODE_PATH_CONTAINER}/backend/
            - ./docker/composer/docker-entrypoint.sh:/docker-entrypoint.sh
        entrypoint: /docker-entrypoint.sh
        working_dir: ${SPA_CODE_PATH_CONTAINER}/backend/
